ALTER TABLE "referral_tickets"
  ADD COLUMN IF NOT EXISTS "entityType" TEXT,
  ADD COLUMN IF NOT EXISTS "customerRole" TEXT,
  ADD COLUMN IF NOT EXISTS "companyName" TEXT,
  ADD COLUMN IF NOT EXISTS "contactPerson" TEXT,
  ADD COLUMN IF NOT EXISTS "customerCountry" TEXT DEFAULT 'Tanzania',
  ADD COLUMN IF NOT EXISTS "customerRegion" TEXT,
  ADD COLUMN IF NOT EXISTS "customerCity" TEXT,
  ADD COLUMN IF NOT EXISTS "customerEmail" TEXT,
  ADD COLUMN IF NOT EXISTS "customerWebsite" TEXT,
  ADD COLUMN IF NOT EXISTS "relationshipWithCustomer" TEXT,
  ADD COLUMN IF NOT EXISTS "spokenToCustomer" TEXT,
  ADD COLUMN IF NOT EXISTS "customerInterestLevel" TEXT,
  ADD COLUMN IF NOT EXISTS "lumoMayContact" TEXT,
  ADD COLUMN IF NOT EXISTS "customerSuitability" TEXT,
  ADD COLUMN IF NOT EXISTS "relevantCapabilities" TEXT[],
  ADD COLUMN IF NOT EXISTS "supportingDocuments" JSONB,
  ADD COLUMN IF NOT EXISTS "isDuplicatePotential" BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS "declarationAccepted" BOOLEAN DEFAULT false;
