import {
  PartnerOpportunitySummary,
  JoinedDealItem,
  PartnerLeadItem,
  PartnerDealRoom,
  PartnerPerformanceMetrics,
  PartnerTrackingLinkItem,
  PartnerEarningsRecord,
  PartnerPayoutRequest,
  PartnerScoreDetail,
  PartnerPayoutMethod,
  PartnerSubscriptionPlan,
  PartnerKYCProfile,
} from './types'

export const MOCK_PARTNER_OPPORTUNITIES: PartnerOpportunitySummary[] = [
  {
    id: 'opp_1',
    slug: 'power-next-1000-homes',
    title: 'Power the Next 1,000 Homes in Coastal Region',
    businessName: 'Kijani Solar Tech',
    isBusinessVerified: true,
    category: 'Renewable Energy',
    region: 'Coastal & Dar es Salaam',
    type: 'CUSTOMER_ACQUISITION',
    rewardDisplay: 'TZS 45,000 / Installation',
    rewardValueTZS: 45000,
    activePartnersCount: 42,
    closingDate: '31 Dec 2026',
    isSaved: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=60',
    promoVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    publicSummary: 'Earn verified commissions by introducing off-grid households and SMEs to Pay-As-You-Go solar kits in Dar es Salaam, Pwani, and Morogoro.',
    confidentialTerms: {
      subscriberDescription: 'Full verified sales campaign: Free POS demonstration kit, flyer packs, and 30-day cookie attribution with STK down-payment confirmation.',
      commissionRatePercent: 12,
      milestoneBonuses: 'TZS 200,000 bonus on 10th verified installation in a month.',
      attributionWindowDays: 30,
      qualifyingDeliverables: 'Verified installation with customer NIDA copy and first STK payment.',
      evidenceRequired: 'Technician activation ref and signed warranty contract.',
    },
  },
  {
    id: 'opp_2',
    slug: 'mobipay-merchant-onboarding',
    title: 'MobiPay Africa Merchant POS Terminal Distribution',
    businessName: 'MobiPay Africa',
    isBusinessVerified: true,
    category: 'FinTech & Payments',
    region: 'National (Tanzania)',
    type: 'LEAD_GENERATION',
    rewardDisplay: 'TZS 120,000 / Merchant',
    rewardValueTZS: 120000,
    activePartnersCount: 88,
    closingDate: '15 Nov 2026',
    isSaved: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=60',
    promoVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    publicSummary: 'Onboard retail shops, pharmacies, and restaurants to accept QR mobile money payments and card tap terminals.',
    confidentialTerms: {
      subscriberDescription: 'Direct B2B merchant acquisition: Partner receives dedicated merchant QR kits and fast 24h bank settlement verification.',
      attributionWindowDays: 45,
      qualifyingDeliverables: 'Merchant completes first 5 live mobile money transactions on device.',
      evidenceRequired: 'Merchant BRELA/TIN copy and first settlement statement.',
    },
  },
  {
    id: 'opp_3',
    slug: 'safaribox-serengeti-travel',
    title: 'SafariBox Serengeti Luxury Eco-Camp Bookings',
    businessName: 'SafariBox Serengeti',
    isBusinessVerified: true,
    category: 'Travel & Hospitality',
    region: 'Arusha & Northern Circuit',
    type: 'COMMERCIAL_DEAL',
    rewardDisplay: '15% Commission (Avg TZS 450,000)',
    rewardValueTZS: 450000,
    activePartnersCount: 19,
    closingDate: '28 Feb 2027',
    isSaved: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&auto=format&fit=crop&q=60',
    publicSummary: 'High-yield travel bookings for regional lodges and guided wildlife safari excursions.',
    confidentialTerms: {
      subscriberDescription: 'Exclusive travel creator program: High-res visual asset library, guest discount promo codes, and dedicated booking coordinator.',
      commissionRatePercent: 15,
      attributionWindowDays: 60,
      qualifyingDeliverables: 'Guest pays non-refundable safari deposit via bank wire or card.',
      evidenceRequired: 'Booking reservation reference and invoice clearance.',
    },
  },
]

export const MOCK_JOINED_DEALS: JoinedDealItem[] = [
  {
    id: 'joined_1',
    opportunityId: 'opp_1',
    title: 'Power the Next 1,000 Homes in Coastal Region',
    businessName: 'Kijani Solar Tech',
    category: 'Renewable Energy',
    status: 'ACTIVE',
    joinedDate: '12 May 2026',
    rewardDisplay: 'TZS 45,000 / Installation',
    rewardValueTZS: 45000,
    trackingLink: 'https://lumo.co.tz/d/power-next-1000-homes?partner=alex_m',
    referralId: 'LUMO-ALEX-9921',
    promoCode: 'ALEXSOLAR26',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://lumo.co.tz/d/power-next-1000-homes?partner=alex_m',
    activeLeadsCount: 14,
    verifiedConversionsCount: 7,
    earningsEarnedTZS: 315000,
    deliverablesSummary: 'Verified installation with customer NIDA copy and first STK down-payment.',
    evidenceRequired: 'Technician activation code and customer contact match.',
    milestoneProgressPercent: 70,
    canExit: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'joined_2',
    opportunityId: 'opp_2',
    title: 'MobiPay Africa Merchant POS Terminal Distribution',
    businessName: 'MobiPay Africa',
    category: 'FinTech & Payments',
    status: 'ACTIVE',
    joinedDate: '01 June 2026',
    rewardDisplay: 'TZS 120,000 / Merchant',
    rewardValueTZS: 120000,
    trackingLink: 'https://lumo.co.tz/d/mobipay-pos?partner=alex_m',
    referralId: 'LUMO-ALEX-POS88',
    promoCode: 'MOBIALEX',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://lumo.co.tz/d/mobipay-pos?partner=alex_m',
    activeLeadsCount: 4,
    verifiedConversionsCount: 2,
    earningsEarnedTZS: 240000,
    deliverablesSummary: 'Merchant completes 5 live transactions after POS handover.',
    evidenceRequired: 'Merchant onboarding agreement copy and serial number.',
    milestoneProgressPercent: 40,
    canExit: true,
    coverImageUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&auto=format&fit=crop&q=60',
  },
  {
    id: 'joined_3',
    opportunityId: 'opp_3',
    title: 'SafariBox Serengeti Luxury Eco-Camp Bookings',
    businessName: 'SafariBox Serengeti',
    category: 'Travel & Hospitality',
    status: 'AWAITING_APPROVAL',
    joinedDate: 'Yesterday',
    rewardDisplay: '15% Commission (Avg TZS 450,000)',
    rewardValueTZS: 450000,
    trackingLink: 'https://lumo.co.tz/d/safaribox?partner=alex_m',
    referralId: 'LUMO-ALEX-SAFARI',
    promoCode: 'SAFARIALEX',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://lumo.co.tz/d/safaribox?partner=alex_m',
    activeLeadsCount: 0,
    verifiedConversionsCount: 0,
    earningsEarnedTZS: 0,
    deliverablesSummary: 'Direct guest booking with confirmed lodge deposit.',
    evidenceRequired: 'Reservation confirmation copy.',
    milestoneProgressPercent: 0,
    canExit: false,
    coverImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=800&auto=format&fit=crop&q=60',
  },
]

export const MOCK_PARTNER_LEADS: PartnerLeadItem[] = [
  {
    id: 'lead_1',
    dealId: 'joined_1',
    dealTitle: 'Power the Next 1,000 Homes in Coastal Region',
    businessName: 'Kijani Solar Tech',
    customerName: 'Hassan M. Kibwana',
    customerPhoneMasked: '+255 754 *** 892',
    customerEmail: 'hassan.kibwana@gmail.com',
    productInterested: 'Solar Home Kit 200W (Pay-As-You-Go)',
    referralDate: 'Today, 11:20 AM',
    estimatedValueTZS: 380000,
    status: 'QUALIFIED',
    consentConfirmed: true,
    notes: 'Customer visited shop in Bagamoyo; confirmed installation for Saturday.',
    evidenceFileName: 'bagamoyo_contract_401.pdf',
    earnedRewardTZS: 45000,
    updatedAt: 'Today, 11:45 AM',
  },
  {
    id: 'lead_2',
    dealId: 'joined_1',
    dealTitle: 'Power the Next 1,000 Homes in Coastal Region',
    businessName: 'Kijani Solar Tech',
    customerName: 'Neema Josephat',
    customerPhoneMasked: '+255 768 *** 119',
    productInterested: 'Solar Home Kit 100W',
    referralDate: 'Yesterday, 04:15 PM',
    estimatedValueTZS: 250000,
    status: 'VALIDATING',
    consentConfirmed: true,
    notes: 'Down-payment STK push sent to customer phone.',
    updatedAt: 'Yesterday, 04:30 PM',
  },
  {
    id: 'lead_3',
    dealId: 'joined_2',
    dealTitle: 'MobiPay Africa Merchant POS Terminal Distribution',
    businessName: 'MobiPay Africa',
    customerName: 'Baraka Hardware & Electricals (Mr. Baraka)',
    customerPhoneMasked: '+255 784 *** 900',
    productInterested: 'Android Smart POS Terminal (Dual SIM)',
    referralDate: '20 Aug 2026',
    estimatedValueTZS: 800000,
    status: 'CONVERTED',
    consentConfirmed: true,
    notes: 'Merchant completed EWURA inspection and 10 transactions.',
    earnedRewardTZS: 120000,
    updatedAt: '22 Aug 2026',
  },
  {
    id: 'lead_4',
    dealId: 'joined_1',
    dealTitle: 'Power the Next 1,000 Homes in Coastal Region',
    businessName: 'Kijani Solar Tech',
    customerName: 'Invalid Anonymous Contact',
    customerPhoneMasked: '+255 700 *** 000',
    productInterested: 'Solar Home Kit',
    referralDate: '15 Aug 2026',
    estimatedValueTZS: 380000,
    status: 'REJECTED',
    consentConfirmed: false,
    rejectionReason: 'Invalid phone number screening failed; duplicate entry detected.',
    appealStatus: 'NONE',
    updatedAt: '16 Aug 2026',
  },
]

export const MOCK_PARTNER_DEAL_ROOMS: PartnerDealRoom[] = [
  {
    id: 'room_p1',
    dealTitle: 'Lake Zone Regional Wholesale Distributor Search',
    businessName: 'Kijani Solar Tech Ltd',
    stage: 'TERMS_AGREED',
    agreedBountyTZS: 1500000,
    contractSigned: true,
    deliverables: 'Signed 1-year distribution agreement for Mwanza & Kagera regions with initial 100-unit stock order.',
    lastMessage: 'Digital distribution agreement countersigned. Milestone 1 active.',
    lastUpdated: 'Today, 01:15 PM',
  },
]

export const MOCK_PARTNER_PERFORMANCE: PartnerPerformanceMetrics = {
  verifiedClicks: 1420,
  qualifiedLeads: 18,
  verifiedConversions: 7,
  revenueGeneratedTZS: 3850000,
  conversionRatePercent: 4.9,
  averageDealValueTZS: 550000,
  approvedRewardsTZS: 485000,
  rejectedResultsCount: 1,
  reversalsCount: 0,
  milestoneProgressPercent: 78,
  partnerScore: 96,
}

export const MOCK_TRACKING_LINKS: PartnerTrackingLinkItem[] = [
  {
    id: 'trk_p1',
    dealTitle: 'Power the Next 1,000 Homes in Coastal Region',
    url: 'https://lumo.co.tz/d/power-next-1000-homes?partner=alex_m',
    promoCode: 'ALEXSOLAR26',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://lumo.co.tz/d/power-next-1000-homes?partner=alex_m',
    clicks: 890,
    conversions: 7,
    conversionRate: '5.2%',
    attributionWindowDays: 30,
    isActive: true,
    createdAt: '12 May 2026',
  },
  {
    id: 'trk_p2',
    dealTitle: 'MobiPay Africa Merchant POS Terminal Distribution',
    url: 'https://lumo.co.tz/d/mobipay-pos?partner=alex_m',
    promoCode: 'MOBIALEX',
    qrCodeUrl: 'https://api.qrserver.com/v1/create-qr-code/?size=250x250&data=https://lumo.co.tz/d/mobipay-pos?partner=alex_m',
    clicks: 530,
    conversions: 2,
    conversionRate: '3.8%',
    attributionWindowDays: 45,
    isActive: true,
    createdAt: '01 June 2026',
  },
]

export const MOCK_PARTNER_EARNINGS: PartnerEarningsRecord[] = [
  {
    id: 'earn_1',
    referenceId: 'REW-2026-8812',
    dealTitle: 'Power the Next 1,000 Homes in Coastal Region',
    businessName: 'Kijani Solar Tech',
    grossRewardTZS: 45000,
    taxWithheldTZS: 2250, // 5% TRA
    platformFeeTZS: 0,
    netRewardTZS: 42750,
    status: 'PAYABLE',
    trackedDate: 'Today, 11:45 AM',
    payoutDate: '28 Aug 2026 (Scheduled Batch)',
  },
  {
    id: 'earn_2',
    referenceId: 'REW-2026-8790',
    dealTitle: 'MobiPay Africa Merchant POS Terminal Distribution',
    businessName: 'MobiPay Africa',
    grossRewardTZS: 120000,
    taxWithheldTZS: 6000,
    platformFeeTZS: 0,
    netRewardTZS: 114000,
    status: 'PAYABLE',
    trackedDate: '22 Aug 2026',
    payoutDate: '28 Aug 2026 (Scheduled Batch)',
  },
  {
    id: 'earn_3',
    referenceId: 'REW-2026-8600',
    dealTitle: 'Power the Next 1,000 Homes in Coastal Region',
    businessName: 'Kijani Solar Tech',
    grossRewardTZS: 135000,
    taxWithheldTZS: 6750,
    platformFeeTZS: 0,
    netRewardTZS: 128250,
    status: 'PAID',
    trackedDate: '10 Aug 2026',
    payoutDate: '15 Aug 2026 (Disbursed)',
    payoutMethod: 'Vodacom M-Pesa (+255 754 *** 892)',
  },
]

export const MOCK_PAYOUT_REQUESTS: PartnerPayoutRequest[] = [
  {
    id: 'pay_req_1',
    requestedAt: '22 Aug 2026, 03:30 PM',
    amountTZS: 285000,
    taxWithheldTZS: 14250,
    netAmountTZS: 270750,
    payoutMethod: 'Vodacom M-Pesa STK Push',
    accountNumberMasked: '+255 754 *** 892',
    status: 'APPROVED',
    referenceNumber: 'LUMO-PAY-2026-W08-41',
  },
  {
    id: 'pay_req_2',
    requestedAt: '14 Aug 2026, 10:00 AM',
    amountTZS: 135000,
    taxWithheldTZS: 6750,
    netAmountTZS: 128250,
    payoutMethod: 'Vodacom M-Pesa STK Push',
    accountNumberMasked: '+255 754 *** 892',
    status: 'PAID',
    referenceNumber: 'VOD-B2C-88190021',
  },
]

export const MOCK_PARTNER_SCORE: PartnerScoreDetail = {
  overallScore: 96,
  tierName: 'Diamond Elite Commercial Seller',
  conversionQualityPercent: 99.2,
  responsivenessScore: 98,
  complianceRating: 5.0,
  completedDealsCount: 24,
  tipsToLevelUp: [
    'Complete the "B2B Legal Contracting & SLA Masterclass" in Training Center (+2 points)',
    'Keep customer lead screening response times under 2 hours',
    'Ensure all offline POS receipts have legible customer NIDA numbers',
  ],
}

export const MOCK_PAYOUT_METHODS: PartnerPayoutMethod[] = [
  {
    id: 'pm_1',
    type: 'VODACOM_MPESA',
    accountTitle: 'Alex Mwamburi (Personal)',
    accountNumberMasked: '+255 754 *** 892',
    isDefault: true,
    isVerified: true,
  },
  {
    id: 'pm_2',
    type: 'CRDB_BANK',
    accountTitle: 'Alex Mwamburi',
    accountNumberMasked: 'CRDB 0150 *** 8812',
    isDefault: false,
    isVerified: true,
  },
]

export const MOCK_PARTNER_SUBSCRIPTION: PartnerSubscriptionPlan = {
  planName: 'Semi-Annual Verified Access Pass',
  status: 'ACTIVE',
  daysRemaining: 124,
  priceTZS: 75000,
  cycle: 'SEMI_ANNUAL',
  expiryDate: '28 Dec 2026',
  autoRenew: true,
}

export const MOCK_PARTNER_KYC: PartnerKYCProfile = {
  fullName: 'Alex Mwamburi',
  phoneMasked: '+255 754 *** 892',
  email: 'alex.m@lumopartner.co.tz',
  partnerType: 'SALES_AGENT',
  nidaNumberMasked: '19920814-14120-00001-**',
  tinNumberMasked: '148-291-***',
  isIdentityVerified: true,
  region: 'Dar es Salaam & Pwani',
  channels: ['Direct WhatsApp Field Network', 'Community SACCOS', 'B2B Retail Agents'],
  audienceSize: '12,500 active contacts',
}
