'use client'
import { useCallback, useEffect, useState } from 'react'
import { eat, tzs } from '@/components/hot-deals/HotDealsSection'

type ReviewDeal = { id: string; status: string; teaserTitle: string; inventoryAvailable: number; inventoryTotal: number; rewardBudget: string; rewardRemaining: string; ownerEvidenceFileId: string; partnerReleaseAt: string | null; opportunity: { organization: { legalName: string } }; claims: { id: string; evidenceFileIds: string[]; conversionId: string | null; disputed: boolean }[] }
export default function AdminHotDeals() {
  const [deals, setDeals] = useState<ReviewDeal[]>([])
  const [message, setMessage] = useState('Loading compliance queue…')
  const [busy, setBusy] = useState(false)
  const load = useCallback(async () => { const r = await fetch('/api/hot-deals/admin'); const data = await r.json(); if (!r.ok) throw new Error(data.error); setDeals(data.deals); setMessage(data.deals.length ? '' : 'No deals awaiting review.') }, [])
  useEffect(() => { const initial = setTimeout(() => { void load().catch(e => setMessage(e.message)) }, 0); return () => clearTimeout(initial) }, [load])
  const action = async (id: string, body: object) => {
    setBusy(true)
    try { const r = await fetch(`/api/hot-deals/${id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const data = await r.json(); if (!r.ok) throw new Error(data.error); await load(); setMessage('Action recorded in the audit trail.') }
    catch (e) { setMessage(e instanceof Error ? e.message : 'Action failed.') } finally { setBusy(false) }
  }
  return <main className="mx-auto max-w-5xl space-y-5 px-4 py-8"><h1 className="text-3xl font-bold">Private Hot Deals · Compliance</h1><p className="text-sm text-slate-500">Review authority evidence and commercial terms before publication. Funding must be confirmed through licensed payment partner rails.</p>{message && <p role="status" className="rounded-xl border bg-white p-4 text-sm">{message}</p>}{deals.map(deal => <section key={deal.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{deal.teaserTitle}</h2><p className="mt-1 text-sm text-slate-500">{deal.opportunity.organization.legalName}</p></div><span className="text-sm font-bold text-orange-700">{deal.status.replaceAll('_', ' ')}</span></div><p className="mt-4 text-sm">{deal.inventoryAvailable} / {deal.inventoryTotal} units · Remaining reward budget {tzs(deal.rewardRemaining)} / {tzs(deal.rewardBudget)}</p>{deal.partnerReleaseAt && <p className="mt-2 text-sm">Partner release: {eat(deal.partnerReleaseAt)}</p>}<a href={`/api/hot-deals/admin/files/${deal.ownerEvidenceFileId}`} className="mt-3 inline-block text-sm text-orange-700 underline">Review ownership evidence</a>
      <form className="mt-5 grid gap-3 sm:grid-cols-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action(deal.id, { action: 'state', status: f.get('status'), reason: f.get('reason') }) }}><select name="status" aria-label="New deal state" className="rounded-xl border p-3 text-sm">{['VERIFIED', 'DRAFT', 'PAUSED', 'CANCELLED', 'CLOSED', 'PRIVATE_HOT_DEAL', 'PARTNER_RELEASE'].map(s => <option key={s}>{s}</option>)}</select><input name="reason" required minLength={10} maxLength={1000} placeholder="Decision reason" aria-label="Decision reason" className="rounded-xl border p-3 text-sm" /><button disabled={busy} className="rounded-xl bg-slate-900 p-3 text-sm font-semibold text-white">Record decision</button></form>
      {deal.status === 'VERIFIED' && <form className="mt-4 grid gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action(deal.id, { action: 'publish', startAt: f.get('startAt'), paymentAttemptId: f.get('payment'), reason: f.get('reason') }) }}><label className="text-sm">Release time (ISO timestamp with EAT offset, e.g. 2026-09-10T09:00:00+03:00)<input name="startAt" required className="mt-1 w-full rounded-xl border p-3" /></label><input name="payment" required placeholder="Confirmed payment attempt UUID" aria-label="Funding payment ID" className="rounded-xl border p-3 text-sm" /><input name="reason" required minLength={10} placeholder="Publication reason" aria-label="Publication reason" className="rounded-xl border p-3 text-sm" /><button disabled={busy} className="rounded-xl bg-orange-600 p-3 text-sm font-semibold text-white">Schedule funded publication</button></form>}
      {deal.claims.map(claim => <details key={claim.id} className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-semibold">Referral {claim.id.slice(0, 8)} · {claim.conversionId ? 'Validated' : 'Awaiting validation'}{claim.disputed ? ' · DISPUTED' : ''}</summary><div className="mt-3">{claim.evidenceFileIds.map(file => <a key={file} className="mr-4 text-sm text-orange-700 underline" href={`/api/hot-deals/admin/files/${file}`}>Review evidence</a>)}</div>{!claim.conversionId && <form className="mt-4 grid gap-3" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action(deal.id, { action: 'validate', claimId: claim.id, evidenceFileIds: claim.evidenceFileIds, paymentReference: f.get('reference'), valueMinor: f.get('value'), reason: f.get('reason'), paymentConfirmed: true, signedAgreementConfirmed: f.has('signed'), fraudChecks: { duplicateCustomer: true, selfReferral: true, devicesAndPatterns: true, collusion: true, documents: true, merchantConfirmed: true } }) }}><input name="reference" required placeholder="Verified bank / PSP payment reference" aria-label="Payment reference" className="rounded-xl border p-3 text-sm" /><input name="value" required pattern="[1-9][0-9]*" placeholder="Verified transaction value in minor units (TZS × 100)" aria-label="Transaction minor units" className="rounded-xl border p-3 text-sm" /><input name="reason" required minLength={10} placeholder="Validation findings" aria-label="Validation findings" className="rounded-xl border p-3 text-sm" /><label className="flex gap-2 text-sm"><input type="checkbox" required />I checked duplicate customers, self-referrals, devices, suspicious patterns, collusion and evidence integrity, and confirmed payment with the merchant.</label><label className="flex gap-2 text-sm"><input name="signed" type="checkbox" />Signed agreement confirmed (required for rentals).</label><button disabled={busy || !claim.evidenceFileIds.length} className="rounded-xl bg-orange-600 p-3 text-sm font-semibold text-white">Validate commercial outcome</button></form>}{claim.disputed && <form className="mt-4 flex gap-3" onSubmit={e => { e.preventDefault(); void action(deal.id, { action: 'dispute', claimId: claim.id, reason: new FormData(e.currentTarget).get('reason'), resolve: true }) }}><input name="reason" minLength={10} required placeholder="Evidence-based resolution" aria-label="Resolution reason" className="min-w-0 flex-1 rounded-xl border p-3 text-sm" /><button disabled={busy} className="rounded-xl border p-3 text-sm">Resolve dispute</button></form>}</details>)}
    </section>)}</main>
}
