'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import { MembershipGettingStarted } from '@/components/hot-deals/MembershipGettingStarted'
import { eat, HotDealsSection, type Teaser, tzs } from '@/components/hot-deals/HotDealsSection'

type Account = { access: { privateMember: boolean; partner: boolean; canManageDeals: boolean }; subscriptions: { status: string; expiresAt: string | null; plan: { name: string } }[]; participations: { id: string; status: string; deal: Teaser }[];
  rewards: { id: string; status: string; grossAmountMinor: string; netAmountMinor: string }[];
  payouts: { id: string; status: string; netAmountMinor: string; createdAt: string }[];
  notifications: { id: string; title: string; body: string }[]; saved: Teaser[]; preferences: { inApp: boolean; email: boolean; sms: boolean } | null }
export default function AccountPage() {
  const [data, setData] = useState<Account | null>(null)
  const [message, setMessage] = useState('')
  useEffect(() => { const controller = new AbortController(); void fetch('/api/hot-deals/account', { signal: controller.signal, cache: 'no-store' }).then(async r => { const value = await r.json(); if (!r.ok) throw new Error(value.error); setData(value) }).catch(e => { if (!controller.signal.aborted) setMessage(e.message) }); return () => controller.abort() }, [])
  if (!data) return <main className="mx-auto max-w-xl p-8"><h1 className="text-2xl font-bold">My Private Member & Partner access</h1><p className="mt-4" role="status">{message || 'Loading your account…'}</p>{message && <Link href="/signin" className="mt-4 block text-orange-700">Sign in to continue</Link>}</main>
  if (!data.access.partner && !data.participations.length && !data.rewards.length && !data.payouts.length && !data.saved.length && !data.notifications.length) return <MembershipGettingStarted canManageDeals={data.access.canManageDeals} />
  return <main className="mx-auto max-w-7xl space-y-6 px-4 py-8"><div><h1 className="text-3xl font-bold">Your opportunities, in one place.</h1><p className="mt-2 text-slate-500">Private Member & Partner access</p></div>
    <section className="rounded-2xl border bg-white p-5"><h2 className="font-bold">Subscription & renewal</h2>{data.subscriptions.length ? data.subscriptions.map((s, i) => <p key={i} className="mt-2 text-sm">{s.plan.name} · {s.status}{s.expiresAt && ` · Expires ${eat(s.expiresAt)}`}</p>) : <p className="mt-2 text-sm text-slate-500">No subscription found.</p>}<Link href="/subscriptions" className="mt-3 inline-block text-sm font-semibold text-orange-700">Manage subscription →</Link><p className="mt-3 text-xs text-slate-500">Historical earnings, payout records and dispute access remain available when a subscription expires.</p></section>
    <section className="grid gap-4 sm:grid-cols-3">{[{ title: 'Pending rewards', statuses: ['TRACKED', 'PENDING', 'VALIDATING', 'APPROVED'] }, { title: 'Payable rewards', statuses: ['PAYABLE'] }, { title: 'Paid rewards', statuses: ['PAID'] }].map(group => <div key={group.title} className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{group.title}</p><p className="mt-2 text-2xl font-bold">{tzs(data.rewards.filter(r => group.statuses.includes(r.status)).reduce((sum, r) => sum + BigInt(r.netAmountMinor), 0n).toString())}</p></div>)}</section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Activated deals</h2>{!data.participations.length && <p className="mt-3 text-sm text-slate-500">Activate an eligible opportunity to get started.</p>}<div className="mt-4 grid gap-3 sm:grid-cols-2">{data.participations.map(p => <Link href={`/hot-deals/${p.deal.id}`} key={p.id} className="rounded-xl border p-4"><p className="font-semibold">{p.deal.title}</p><p className="mt-1 text-xs text-slate-500">{p.status} · {p.deal.status.replaceAll('_', ' ')}</p></Link>)}</div><Link href="/hot-deals/history" className="mt-4 inline-block text-sm text-orange-700">Completed deals, evidence & disputes →</Link></section>
    <HotDealsSection compact />
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Saved deals</h2>{data.saved.length ? data.saved.map(d => <Link className="mt-3 block text-sm text-orange-700" key={d.id} href={`/hot-deals/${d.id}`}>{d.title}</Link>) : <p className="mt-3 text-sm text-slate-500">No saved deals yet.</p>}</section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Historical payout records</h2>{!data.payouts.length && <p className="mt-3 text-sm text-slate-500">No payout records yet.</p>}{data.payouts.map(p => <p key={p.id} className="mt-3 border-t pt-3 text-sm">{tzs(p.netAmountMinor)} · {p.status} · {eat(p.createdAt)}</p>)}</section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Notifications</h2>{!data.notifications.length && <p className="mt-3 text-sm text-slate-500">You’re all caught up.</p>}{data.notifications.map(n => <div key={n.id} className="mt-3 border-t pt-3"><p className="text-sm font-semibold">{n.title}</p><p className="mt-1 text-sm text-slate-500">{n.body}</p></div>)}</section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Alert preferences</h2><form className="mt-4 flex flex-wrap items-center gap-5" onSubmit={async e => { e.preventDefault(); const form = new FormData(e.currentTarget); const response = await fetch('/api/hot-deals/account', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ inApp: form.has('inApp'), email: form.has('email'), sms: form.has('sms') }) }); setMessage(response.ok ? 'Preferences saved.' : 'Unable to save preferences.') }}>{(['inApp', 'email', 'sms'] as const).map(channel => <label key={channel} className="flex gap-2 text-sm"><input type="checkbox" name={channel} defaultChecked={data.preferences?.[channel] ?? channel === 'inApp'} />{channel === 'inApp' ? 'In-app' : channel.toUpperCase()}</label>)}<button className="rounded-xl bg-orange-600 px-4 py-2 text-sm font-semibold text-white">Save preferences</button></form><p className="mt-3 text-xs text-slate-500">Email and SMS are sent where delivery is configured.</p>{message && <p role="status" className="mt-3 text-sm">{message}</p>}</section>
  </main>
}

