import {
  BusinessOpportunityItem,
  BusinessPartnerItem,
  BusinessConversionRecord,
  BusinessRewardObligation,
  RewardFundingBalance,
  BusinessCampaignGroup,
  DealRoomSession,
  BusinessTeamMember,
  BusinessSaaSSubscription,
} from './types'

export const MOCK_FUNDING_BALANCE: RewardFundingBalance = {
  availableBalanceTZS: 3250000,
  committedToActiveDealsTZS: 1850000,
  pendingConfirmationTZS: 420000,
  rewardsPayableTZS: 890000,
  rewardsPaidTZS: 14650000,
  refundableBalanceTZS: 1400000,
  safeguardingProvider: 'CRDB Bank Escrow / Vodacom Trust Partner Account',
  lastReconciliationDate: '24 Aug 2026, 02:00 PM (Daily Sync)',
}

export const MOCK_BUSINESS_OPPORTUNITIES: BusinessOpportunityItem[] = [
  {
    id: 'opp_1',
    slug: 'power-next-1000-homes',
    title: 'Power the Next 1,000 Homes in Coastal Region',
    publicSummary: 'Earn commission by introducing off-grid households and SMEs to Pay-As-You-Go Solar Kits.',
    subscriberDescription: 'Exclusive verified campaign: Partners receive full marketing collateral, POS flyers, and dedicated field leads in Dar es Salaam, Pwani, and Morogoro.',
    type: 'CUSTOMER_ACQUISITION',
    category: 'Renewable Energy',
    region: 'Coastal & Dar es Salaam',
    commercialResult: 'COMPLETED_SALE',
    rewardStructure: 'FIXED_REWARD',
    rewardValueTZS: 45000,
    budgetTZS: 45000000,
    spentTZS: 18450000,
    status: 'PUBLISHED',
    version: 2,
    activePartners: 42,
    totalConversions: 410,
    trackingMethod: 'QR_CODE',
    startDate: '2026-06-01',
    endDate: '2026-12-31',
    attributionWindowDays: 30,
    partnerDeliverables: 'Verified installation with customer National ID (NIDA) copy and first STK installment payment.',
    evidenceRequired: 'Installation contract reference and technician activation code.',
    cancellationTerms: '7-day customer cooling period applies before reward approval.',
    coverImageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=60',
    promoVideoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    galleryImageUrls: [
      'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=800&auto=format&fit=crop&q=60',
      'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=800&auto=format&fit=crop&q=60',
    ],
    marketingAssets: [
      { id: 'ast_1', name: 'Kijani Solar Kit Specs & Pricing.pdf', url: '#', size: '2.4 MB', type: 'PDF' },
      { id: 'ast_2', name: 'Partner WhatsApp Promotional Banners.zip', url: '#', size: '8.1 MB', type: 'IMAGE' },
      { id: 'ast_3', name: 'Product Demo & Customer Pitch.mp4', url: '#', size: '24.5 MB', type: 'VIDEO' },
    ],
    createdAt: '2026-05-15',
    campaignId: 'camp_1',
    versionHistory: [
      {
        version: 2,
        amendedAt: '2026-07-01',
        changesDescription: 'Expanded eligible coverage to include Morogoro rural districts.',
        approvedByLumo: 'Given M. (Super Admin)',
        partnerConsentRequired: false,
      },
      {
        version: 1,
        amendedAt: '2026-06-01',
        changesDescription: 'Initial approved publication.',
        approvedByLumo: 'Given M. (Super Admin)',
        partnerConsentRequired: false,
      },
    ],
  },
  {
    id: 'opp_2',
    slug: 'solar-installer-referral-program',
    title: 'Certified Solar Installer & Field Agent Program',
    publicSummary: 'Recruit certified local technicians and vocational school graduates to install community solar microgrids.',
    subscriberDescription: 'B2B field recruitment: Certified electrical technicians receive per-lead onboarding and milestone delivery bonuses.',
    type: 'LEAD_GENERATION',
    category: 'Renewable Energy & Skills',
    region: 'National (Tanzania Mainland)',
    commercialResult: 'QUALIFIED_LEAD',
    rewardStructure: 'COST_PER_LEAD',
    rewardValueTZS: 25000,
    budgetTZS: 15000000,
    spentTZS: 5125000,
    status: 'PUBLISHED',
    version: 1,
    activePartners: 67,
    totalConversions: 205,
    trackingMethod: 'LUMO_TRACKING_LINK',
    startDate: '2026-05-01',
    endDate: '2026-11-30',
    attributionWindowDays: 14,
    partnerDeliverables: 'Technician contact, VETA / EWURA certificate copy, and passed phone screening.',
    evidenceRequired: 'Technician verification portal ID match.',
    cancellationTerms: 'Duplicates or unverified phone numbers rejected within 48h.',
    createdAt: '2026-04-20',
    campaignId: 'camp_1',
  },
  {
    id: 'opp_3',
    slug: 'regional-distributor-search-lake-zone',
    title: 'Lake Zone Regional Wholesale Distributor Search',
    publicSummary: 'High-value commercial introduction bounty for connecting wholesale hardware distributors in Mwanza & Shinyanga.',
    subscriberDescription: 'B2B commercial expansion: Partner receives milestone bonus upon distributor signing MOUs and minimum stock commitment.',
    type: 'B2B_INTRODUCTION',
    category: 'Commercial Distribution',
    region: 'Mwanza & Lake Zone',
    commercialResult: 'SIGNED_DISTRIBUTOR_CONTRACT',
    rewardStructure: 'BOUNTY',
    rewardValueTZS: 1500000,
    budgetTZS: 6000000,
    spentTZS: 1500000,
    status: 'UNDER_REVIEW',
    version: 1,
    activePartners: 0,
    totalConversions: 0,
    trackingMethod: 'MANUAL_EVIDENCE_APPROVAL',
    startDate: '2026-09-01',
    endDate: '2026-12-31',
    attributionWindowDays: 60,
    partnerDeliverables: 'Direct introduction to managing director, hosted discovery call, and signed purchase agreement.',
    evidenceRequired: 'Countersigned distributor contract and initial deposit receipt.',
    cancellationTerms: 'Standard LUMO Deal Room B2B escrow mediation rules apply.',
    createdAt: 'Today, 08:30 AM',
  },
  {
    id: 'opp_4',
    slug: 'clean-cooking-biogas-pilot',
    title: 'Clean Cooking LPG & Biogas Subscriptions (Draft)',
    publicSummary: 'Suburban household clean energy transition campaign.',
    subscriberDescription: 'Subscription model: Earn recurring 10% monthly commission on cylinder delivery refills.',
    type: 'AFFILIATE_PROGRAMME',
    category: 'Clean Cooking',
    region: 'Arusha & Kilimanjaro',
    commercialResult: 'SUBSCRIPTION',
    rewardStructure: 'RECURRING_COMMISSION',
    rewardValueTZS: 15000,
    rewardPercent: 10,
    budgetTZS: 10000000,
    spentTZS: 0,
    status: 'DRAFT',
    version: 1,
    activePartners: 0,
    totalConversions: 0,
    trackingMethod: 'PROMO_CODE',
    startDate: '2026-10-01',
    endDate: '2027-03-31',
    attributionWindowDays: 45,
    partnerDeliverables: 'Customer activates 6-month cylinder subscription.',
    evidenceRequired: 'Mobile app smart meter activation ref.',
    cancellationTerms: 'Cancelable prior to formal LUMO submission.',
    createdAt: 'Yesterday',
  },
]

export const MOCK_BUSINESS_PARTNERS: BusinessPartnerItem[] = [
  {
    id: 'prt_1',
    partnerName: 'Amina Selemani',
    partnerType: 'SALES_AGENT',
    avatar: 'AS',
    phoneMasked: '+255 754 *** 892',
    channels: ['Direct WhatsApp', 'Community Groups', 'Local SACCOS'],
    region: 'Dar es Salaam & Pwani',
    performanceScore: 98,
    completedDeals: 14,
    conversionQuality: '99.2%',
    cancellationRate: '0.8%',
    businessRating: 5.0,
    appliedOpportunityId: 'opp_1',
    appliedOpportunityTitle: 'Power the Next 1,000 Homes in Coastal Region',
    applicationDate: '12 May 2026',
    applicationPitch: 'I lead a network of 40 rural women community leaders in Bagamoyo and Kibaha. We have already sold 85 solar kits.',
    status: 'ACTIVE',
    joinedProgramDate: '14 May 2026',
    totalEarnedTZS: 3825000,
    verifiedConversionsCount: 85,
  },
  {
    id: 'prt_2',
    partnerName: 'Juma K. Mwamburi',
    partnerType: 'CONTENT_CREATOR',
    avatar: 'JM',
    phoneMasked: '+255 768 *** 119',
    channels: ['YouTube (Tech Review)', 'Instagram (120k)', 'TikTok Tech TZ'],
    region: 'National',
    performanceScore: 94,
    completedDeals: 8,
    conversionQuality: '97.5%',
    cancellationRate: '2.5%',
    businessRating: 4.8,
    appliedOpportunityId: 'opp_1',
    appliedOpportunityTitle: 'Power the Next 1,000 Homes in Coastal Region',
    applicationDate: '18 May 2026',
    applicationPitch: 'Created unboxing and installation review video featuring Kijani Solar Home Kit with dynamic promo code link.',
    status: 'ACTIVE',
    joinedProgramDate: '20 May 2026',
    totalEarnedTZS: 2250000,
    verifiedConversionsCount: 50,
  },
  {
    id: 'prt_3',
    partnerName: 'Baraka Distribution Co.',
    partnerType: 'DISTRIBUTOR',
    avatar: 'BD',
    phoneMasked: '+255 784 *** 900',
    channels: ['Wholesale Hardware Stores', 'Agri-input Dealers'],
    region: 'Mwanza & Shinyanga',
    performanceScore: 91,
    completedDeals: 3,
    conversionQuality: '100%',
    cancellationRate: '0.0%',
    businessRating: 4.9,
    appliedOpportunityId: 'opp_3',
    appliedOpportunityTitle: 'Lake Zone Regional Wholesale Distributor Search',
    applicationDate: 'Yesterday, 04:15 PM',
    applicationPitch: 'We operate 6 supply warehouses across Lake Zone and supply over 200 secondary retailers.',
    status: 'APPLIED',
    totalEarnedTZS: 0,
    verifiedConversionsCount: 0,
  },
  {
    id: 'prt_4',
    partnerName: 'Elias N. Ndunguru',
    partnerType: 'AFFILIATE',
    avatar: 'EN',
    phoneMasked: '+255 712 *** 331',
    channels: ['Telegram Energy Deals', 'Facebook Page'],
    region: 'Morogoro',
    performanceScore: 86,
    completedDeals: 2,
    conversionQuality: '92.0%',
    cancellationRate: '8.0%',
    businessRating: 4.2,
    appliedOpportunityId: 'opp_2',
    appliedOpportunityTitle: 'Certified Solar Installer & Field Agent Program',
    applicationDate: '3 days ago',
    status: 'SHORTLISTED',
    totalEarnedTZS: 0,
    verifiedConversionsCount: 0,
  },
  {
    id: 'prt_5',
    partnerName: 'Unknown Automated Traffic Botnet',
    partnerType: 'AFFILIATE',
    avatar: 'XB',
    phoneMasked: '+255 700 *** 000',
    channels: ['Spam SMS', 'Scraped Forums'],
    region: 'Unknown',
    performanceScore: 12,
    completedDeals: 0,
    conversionQuality: '0.0%',
    cancellationRate: '100%',
    businessRating: 1.0,
    appliedOpportunityId: 'opp_1',
    appliedOpportunityTitle: 'Power the Next 1,000 Homes in Coastal Region',
    applicationDate: '01 June 2026',
    status: 'BLOCKED',
    totalEarnedTZS: 0,
    verifiedConversionsCount: 0,
  },
]

export const MOCK_BUSINESS_CONVERSIONS: BusinessConversionRecord[] = [
  {
    id: 'conv_1',
    referenceId: 'CONV-2026-8812',
    opportunityId: 'opp_1',
    opportunityTitle: 'Power the Next 1,000 Homes',
    partnerId: 'prt_1',
    partnerName: 'Amina Selemani',
    customerRef: 'CUST-BAGAMOYO-401 (Hassan M.)',
    amountTZS: 380000,
    rewardEarnedTZS: 45000,
    trackingMethod: 'QR_CODE',
    status: 'VERIFIED',
    reportedAt: 'Today, 11:20 AM',
    verifiedAt: 'Today, 11:45 AM (Technician NIDA Match)',
    evidenceUrl: 'https://storage.lumo.co.tz/contracts/bagamoyo_401.pdf',
  },
  {
    id: 'conv_2',
    referenceId: 'CONV-2026-8813',
    opportunityId: 'opp_1',
    opportunityTitle: 'Power the Next 1,000 Homes',
    partnerId: 'prt_2',
    partnerName: 'Juma K. Mwamburi',
    customerRef: 'CUST-DAR-9921 (Neema J.)',
    amountTZS: 450000,
    rewardEarnedTZS: 45000,
    trackingMethod: 'PROMO_CODE',
    status: 'PENDING_VALIDATION',
    reportedAt: 'Today, 10:15 AM',
    evidenceUrl: 'https://storage.lumo.co.tz/receipts/mpesa_stk_8849.pdf',
  },
  {
    id: 'conv_3',
    referenceId: 'CONV-2026-8799',
    opportunityId: 'opp_2',
    opportunityTitle: 'Certified Solar Installer',
    partnerId: 'prt_4',
    partnerName: 'Elias N. Ndunguru',
    customerRef: 'TECH-LEAD-MORO-12 (Daniel K.)',
    amountTZS: 0,
    rewardEarnedTZS: 25000,
    trackingMethod: 'LUMO_TRACKING_LINK',
    status: 'PENDING_VALIDATION',
    reportedAt: 'Yesterday, 03:30 PM',
  },
]

export const MOCK_BUSINESS_REWARDS: BusinessRewardObligation[] = [
  {
    id: 'rew_1',
    conversionRef: 'CONV-2026-8812',
    partnerName: 'Amina Selemani',
    opportunityTitle: 'Power the Next 1,000 Homes',
    grossRewardTZS: 45000,
    status: 'APPROVED',
    dueDate: '2026-08-28',
    funded: true,
  },
  {
    id: 'rew_2',
    conversionRef: 'CONV-2026-8813',
    partnerName: 'Juma K. Mwamburi',
    opportunityTitle: 'Power the Next 1,000 Homes',
    grossRewardTZS: 45000,
    status: 'VALIDATING',
    dueDate: '2026-08-30',
    funded: true,
  },
  {
    id: 'rew_3',
    conversionRef: 'CONV-2026-8700',
    partnerName: 'Amina Selemani',
    opportunityTitle: 'Power the Next 1,000 Homes',
    grossRewardTZS: 45000,
    status: 'PAID',
    dueDate: '2026-08-20',
    funded: true,
  },
]

export const MOCK_BUSINESS_CAMPAIGNS: BusinessCampaignGroup[] = [
  {
    id: 'camp_1',
    title: 'Solar Homes Tanzania 2026 Growth Initiative',
    objective: 'Deploy 5,000 clean energy household kits across mainland Tanzania by Q4 2026.',
    totalBudgetTZS: 60000000,
    spentTZS: 23575000,
    startDate: '2026-05-01',
    endDate: '2026-12-31',
    status: 'ACTIVE',
    associatedOpportunityIds: ['opp_1', 'opp_2', 'opp_3'],
    channels: ['Field Sales Agents', 'YouTube/Instagram Tech Influencers', 'B2B Regional Hardware Distributors'],
    impressions: 245000,
    conversions: 615,
  },
]

export const MOCK_DEAL_ROOMS: DealRoomSession[] = [
  {
    id: 'room_1',
    opportunityTitle: 'Lake Zone Regional Wholesale Distributor Search',
    partnerName: 'Baraka Distribution Co.',
    partnerType: 'Wholesale Commercial Distributor',
    stage: 'TERMS_AGREED',
    currentProposedRewardTZS: 1500000,
    deliverablesSummary: 'Signed 1-year distribution agreement for Mwanza & Kagera regions with 100-unit initial stock order.',
    contractSigned: true,
    messagesCount: 14,
    lastUpdated: 'Today, 01:15 PM',
  },
]

export const MOCK_TEAM_MEMBERS: BusinessTeamMember[] = [
  {
    id: 'team_1',
    name: 'Alex Mushi',
    email: 'alex.mushi@kijanisolar.co.tz',
    role: 'OWNER',
    status: 'ACTIVE',
    lastLogin: 'Just now',
    joinedDate: '15 Jan 2026',
  },
  {
    id: 'team_2',
    name: 'Zawadi Temba',
    email: 'zawadi.t@kijanisolar.co.tz',
    role: 'CAMPAIGN_MANAGER',
    status: 'ACTIVE',
    lastLogin: 'Yesterday, 05:20 PM',
    joinedDate: '01 Feb 2026',
  },
  {
    id: 'team_3',
    name: 'Frank Mgaya',
    email: 'frank.finance@kijanisolar.co.tz',
    role: 'FINANCE_OFFICER',
    status: 'ACTIVE',
    lastLogin: '3 days ago',
    joinedDate: '10 Feb 2026',
  },
]

export const MOCK_SAAS_SUBSCRIPTION: BusinessSaaSSubscription = {
  planName: 'Pro Commercial Growth Tier',
  cycle: 'ANNUAL',
  priceTZS: 1800000,
  status: 'ACTIVE',
  activeOpportunitiesUsed: 3,
  activeOpportunitiesLimit: 10,
  partnerSeatsUsed: 142,
  partnerSeatsLimit: 500,
  aiAttributionIncluded: true,
  nextBillingDate: '15 Jan 2027',
  invoices: [
    {
      invoiceNumber: 'INV-LUMO-2026-0042',
      date: '15 Jan 2026',
      amountTZS: 1800000,
      status: 'PAID',
      pdfUrl: '#',
    },
  ],
}
