import {
  UserAccount,
  BusinessVerificationItem,
  AdminDealItem,
  ConversionRecord,
  SubscriptionTransaction,
  PaymentLedgerItem,
  RewardPayoutBatch,
  ReconciliationRun,
  TaxRuleConfig,
  FraudAlertCase,
  DisputeItem,
  AuditLogEntry,
  WebhookIntegration,
} from './types'

export const MOCK_USERS: UserAccount[] = [
  {
    id: 'usr_001',
    name: 'Alex Mushi',
    email: 'alex.mushi@lumo.co.tz',
    phone: '+255 712 345 678',
    role: 'PARTNER',
    status: 'ACTIVE',
    mfaEnabled: true,
    lastActive: '12 mins ago',
    joinedDate: '15 Jan 2026',
    totalTransactions: 42,
    balanceTZS: 1850000,
    kycStatus: 'VERIFIED',
  },
  {
    id: 'usr_002',
    name: 'Kijani Solar Tech Ltd',
    email: 'info@kijanisolar.co.tz',
    phone: '+255 684 992 110',
    role: 'BUSINESS',
    status: 'ACTIVE',
    mfaEnabled: true,
    lastActive: '1 hour ago',
    joinedDate: '02 Feb 2026',
    totalTransactions: 128,
    balanceTZS: 14200000,
    kycStatus: 'VERIFIED',
  },
  {
    id: 'usr_003',
    name: 'MobiPay Africa',
    email: 'compliance@mobipay.africa',
    phone: '+255 754 112 334',
    role: 'BUSINESS',
    status: 'ACTIVE',
    mfaEnabled: true,
    lastActive: '5 hours ago',
    joinedDate: '20 Feb 2026',
    totalTransactions: 18,
    balanceTZS: 8900000,
    kycStatus: 'UNDER_REVIEW',
  },
  {
    id: 'usr_004',
    name: 'Fatma Juma',
    email: 'fatma.juma@gmail.com',
    phone: '+255 765 889 001',
    role: 'PARTNER',
    status: 'SUSPENDED',
    mfaEnabled: false,
    lastActive: '2 days ago',
    joinedDate: '10 Feb 2026',
    totalTransactions: 4,
    balanceTZS: 45000,
    kycStatus: 'REJECTED',
  },
  {
    id: 'usr_005',
    name: 'Given M. (Admin)',
    email: 'given@lumo.co.tz',
    phone: '+255 784 000 111',
    role: 'ADMIN',
    status: 'ACTIVE',
    mfaEnabled: true,
    lastActive: 'Just now',
    joinedDate: '01 Jan 2026',
    totalTransactions: 0,
    balanceTZS: 0,
    kycStatus: 'VERIFIED',
  },
]

export const MOCK_VERIFICATIONS: BusinessVerificationItem[] = [
  {
    id: 'ver_001',
    businessName: 'MobiPay Africa Ltd',
    registrationNumber: 'BRELA-TZ-184920',
    tinNumber: '148-291-002',
    industry: 'FinTech & Payment Solutions',
    contactPerson: 'Dennis Makawia',
    email: 'dennis@mobipay.africa',
    phone: '+255 754 112 334',
    submittedAt: 'Today, 10:42 AM',
    status: 'SUBMITTED',
    beneficialOwners: ['Dennis Makawia (55%)', 'Grace Temu (45%)'],
    assignedChecker: 'Given M.',
    documents: [
      { name: 'BRELA Certificate of Incorporation', type: 'BRELA_CERT', status: 'PENDING', url: '#' },
      { name: 'TRA Tax Identification Certificate', type: 'TIN_CERT', status: 'PENDING', url: '#' },
      { name: 'TRA Valid Tax Clearance 2026', type: 'TAX_CLEARANCE', status: 'PENDING', url: '#' },
      { name: 'Director National NIDA ID', type: 'ID_PASSPORT', status: 'VERIFIED', url: '#' },
    ],
  },
  {
    id: 'ver_002',
    businessName: 'Kilimo Bora Agrotech',
    registrationNumber: 'BRELA-TZ-982104',
    tinNumber: '139-440-119',
    industry: 'Agri-Business & Supplies',
    contactPerson: 'Baraka Msangi',
    email: 'baraka@kilimobora.co.tz',
    phone: '+255 713 900 882',
    submittedAt: 'Yesterday, 04:15 PM',
    status: 'UNDER_REVIEW',
    beneficialOwners: ['Baraka Msangi (100%)'],
    assignedChecker: 'Given M.',
    documents: [
      { name: 'BRELA Certificate of Incorporation', type: 'BRELA_CERT', status: 'VERIFIED', url: '#' },
      { name: 'TRA Tax Identification Certificate', type: 'TIN_CERT', status: 'VERIFIED', url: '#' },
      { name: 'Director Passport Photo', type: 'ID_PASSPORT', status: 'PENDING', url: '#' },
    ],
  },
  {
    id: 'ver_003',
    businessName: 'Haraka Logistics Express',
    registrationNumber: 'BRELA-TZ-642109',
    tinNumber: '122-801-443',
    industry: 'Transport & Delivery',
    contactPerson: 'Zuberi Bakari',
    email: 'zuberi@haraka.co.tz',
    phone: '+255 788 123 456',
    submittedAt: '2 days ago',
    status: 'MORE_INFO_REQUIRED',
    decisionReason: 'TRA clearance certificate expired in 2025. Please upload latest 2026 clearance.',
    beneficialOwners: ['Zuberi Bakari (70%)', 'Salim Bakari (30%)'],
    documents: [
      { name: 'BRELA Certificate', type: 'BRELA_CERT', status: 'VERIFIED', url: '#' },
      { name: 'TRA Tax Clearance (Expired)', type: 'TAX_CLEARANCE', status: 'INVALID', url: '#' },
    ],
  },
]

export const MOCK_ADMIN_DEALS: AdminDealItem[] = [
  {
    id: 'deal_001',
    slug: 'kijani-solar-home-kit',
    title: 'Kijani Solar: Power Next 1,000 Homes in Coastal Region',
    businessName: 'Kijani Solar Tech Ltd',
    category: 'Renewable Energy',
    type: 'CUSTOMER_ACQUISITION',
    rewardValueTZS: 45000,
    budgetTZS: 45000000,
    spentTZS: 18450000,
    status: 'PUBLISHED',
    version: 2,
    activePartners: 312,
    createdAt: '10 Jan 2026',
    publishedAt: '12 Jan 2026',
  },
  {
    id: 'deal_002',
    slug: 'mobipay-agent-recruitment',
    title: 'MobiPay Nationwide Agency Expansion (Per Approved Agent)',
    businessName: 'MobiPay Africa Ltd',
    category: 'Financial Services',
    type: 'QUALIFIED_LEADS',
    rewardValueTZS: 25000,
    budgetTZS: 25000000,
    spentTZS: 0,
    status: 'UNDER_REVIEW',
    version: 1,
    activePartners: 0,
    createdAt: '22 Feb 2026',
    checkerNotes: 'Maker submitted terms. Escrow balance verification in progress.',
  },
  {
    id: 'deal_003',
    slug: 'kilimo-bora-fertilizer-b2b',
    title: 'Kilimo Bora: Organic Fertilizer Retailer Distributor Search',
    businessName: 'Kilimo Bora Agrotech',
    category: 'Agriculture',
    type: 'DISTRIBUTOR_SEARCH',
    rewardValueTZS: 120000,
    budgetTZS: 12000000,
    spentTZS: 3600000,
    status: 'PUBLISHED',
    version: 1,
    activePartners: 84,
    createdAt: '18 Jan 2026',
    publishedAt: '20 Jan 2026',
  },
]

export const MOCK_CONVERSIONS: ConversionRecord[] = [
  {
    id: 'conv_901',
    dealTitle: 'Kijani Solar: Power Next 1,000 Homes',
    partnerName: 'Alex Mushi',
    partnerCode: 'ALEX-TZ-90',
    channel: 'QR_SCAN',
    referenceId: 'REF-KS-2026-8941',
    customerIdentifier: '+255 714 *** 892',
    amountTZS: 450000,
    commissionTZS: 45000,
    timestamp: 'Today, 11:20 AM',
    status: 'VERIFIED',
    webhookStatus: 'DELIVERED',
    ipAddress: '197.250.48.12',
  },
  {
    id: 'conv_902',
    dealTitle: 'Kijani Solar: Power Next 1,000 Homes',
    partnerName: 'Unknown / Suspicious IP',
    partnerCode: 'BOT-TEST-01',
    channel: 'AFFILIATE_LINK',
    referenceId: 'REF-KS-2026-8942',
    customerIdentifier: '+255 700 *** 000',
    amountTZS: 450000,
    commissionTZS: 45000,
    timestamp: 'Today, 10:55 AM',
    status: 'DUPLICATE_FLAGGED',
    webhookStatus: 'FAILED',
    ipAddress: '41.59.18.99',
  },
  {
    id: 'conv_903',
    dealTitle: 'Kilimo Bora: Organic Fertilizer Retailer',
    partnerName: 'Amina Khatibu',
    partnerCode: 'AMINA-AGRI-12',
    channel: 'MERCHANT_API',
    referenceId: 'INV-KB-77812',
    customerIdentifier: 'Dodoma Agro Cooperative',
    amountTZS: 2400000,
    commissionTZS: 120000,
    timestamp: 'Today, 09:14 AM',
    status: 'TRACKED',
    webhookStatus: 'DELIVERED',
    ipAddress: '196.216.240.10',
  },
]

export const MOCK_SUBSCRIPTION_LEDGER: SubscriptionTransaction[] = [
  {
    id: 'sub_tx_01',
    userId: 'usr_001',
    userName: 'Alex Mushi',
    planCode: 'SEMI_ANNUAL',
    planName: 'Semi-Annual Pro (180 Days)',
    amountTZS: 180000,
    status: 'ACTIVE',
    providerRef: 'MPESA-VOD-881920',
    startsAt: '15 Jan 2026',
    expiresAt: '15 Jul 2026',
    autoRenew: true,
  },
  {
    id: 'sub_tx_02',
    userId: 'usr_006',
    userName: 'Said Rashidi',
    planCode: 'MONTHLY',
    planName: 'Monthly Starter (30 Days)',
    amountTZS: 35000,
    status: 'ACTIVE',
    providerRef: 'TIGO-PESA-449102',
    startsAt: '01 Feb 2026',
    expiresAt: '03 Mar 2026',
    autoRenew: true,
  },
  {
    id: 'sub_tx_03',
    userId: 'usr_007',
    userName: 'Apex Growth Enterprise',
    planCode: 'ENTERPRISE_AI',
    planName: 'Enterprise AI & Custom Attribution',
    amountTZS: 1500000,
    status: 'ACTIVE',
    providerRef: 'CRDB-EFT-99120',
    startsAt: '10 Feb 2026',
    expiresAt: '10 Feb 2027',
    autoRenew: false,
  },
]

export const MOCK_PAYMENTS: PaymentLedgerItem[] = [
  {
    id: 'pay_001',
    reference: 'LUMO-PAY-99120',
    payerName: 'Kijani Solar Tech Ltd',
    payerType: 'BUSINESS',
    channel: 'CRDB_BANK',
    purpose: 'DEAL_ESCROW_FUNDING',
    grossAmountTZS: 45000000,
    processingFeeTZS: 0,
    netAmountTZS: 45000000,
    status: 'SUCCESSFUL',
    createdAt: '12 Jan 2026, 09:30 AM',
    verifiedAt: '12 Jan 2026, 09:32 AM',
  },
  {
    id: 'pay_002',
    reference: 'LUMO-PAY-99144',
    payerName: 'Alex Mushi',
    payerType: 'PARTNER',
    channel: 'VODACOM_MPESA',
    purpose: 'SUBSCRIPTION',
    grossAmountTZS: 180000,
    processingFeeTZS: 1500,
    netAmountTZS: 178500,
    status: 'SUCCESSFUL',
    createdAt: '15 Jan 2026, 02:15 PM',
    verifiedAt: '15 Jan 2026, 02:15 PM',
  },
  {
    id: 'pay_003',
    reference: 'LUMO-PAY-99189',
    payerName: 'David Marwa',
    payerType: 'PARTNER',
    channel: 'AIRTEL_MONEY',
    purpose: 'SUBSCRIPTION',
    grossAmountTZS: 35000,
    processingFeeTZS: 500,
    netAmountTZS: 34500,
    status: 'FAILED',
    createdAt: 'Today, 08:10 AM',
    providerMessage: 'Insufficient wallet balance at provider gateway.',
  },
]

export const MOCK_REWARD_BATCHES: RewardPayoutBatch[] = [
  {
    id: 'batch_001',
    batchNumber: 'LUMO-DISB-2026-W08',
    totalPartners: 84,
    grossPayoutTZS: 14800000,
    withholdingTaxTZS: 740000, // 5% TRA
    netPayoutTZS: 14060000,
    status: 'APPROVED_CHECKER',
    createdAt: 'Today, 08:30 AM',
    makerName: 'Finance Officer (Asha)',
    checkerName: 'Super Admin (Given)',
  },
  {
    id: 'batch_002',
    batchNumber: 'LUMO-DISB-2026-W07',
    totalPartners: 142,
    grossPayoutTZS: 28400000,
    withholdingTaxTZS: 1420000,
    netPayoutTZS: 26980000,
    status: 'COMPLETED',
    createdAt: '16 Feb 2026',
    disbursedAt: '17 Feb 2026, 11:00 AM',
    makerName: 'Finance Officer (Asha)',
    checkerName: 'Super Admin (Given)',
  },
]

export const MOCK_RECONCILIATION: ReconciliationRun[] = [
  {
    id: 'rec_001',
    period: 'February 2026 (Week 3)',
    provider: 'Vodacom M-Pesa B2C Gateway',
    systemTotalTZS: 34200000,
    providerTotalTZS: 34200000,
    varianceTZS: 0,
    matchedCount: 218,
    unmatchedCount: 0,
    status: 'CLOSED',
    createdAt: '18 Feb 2026',
    closedAt: '19 Feb 2026',
    closedBy: 'Given M.',
  },
  {
    id: 'rec_002',
    period: 'February 2026 (Week 4)',
    provider: 'Tigo Pesa Merchant Collections',
    systemTotalTZS: 18450000,
    providerTotalTZS: 18400000,
    varianceTZS: 50000,
    matchedCount: 124,
    unmatchedCount: 1,
    status: 'ADJUSTMENT_REQUIRED',
    createdAt: 'Today, 06:00 AM',
  },
]

export const MOCK_TAX_RULES: TaxRuleConfig[] = [
  {
    id: 'tax_001',
    code: 'TRA_WITHHOLDING_5',
    title: 'Tanzania Revenue Authority (TRA) Commission Withholding Tax',
    ratePercent: 5.0,
    applicableTo: 'PARTNER_COMMISSION',
    effectiveFrom: '01 Jan 2026',
    authority: 'TRA',
    isActive: true,
  },
  {
    id: 'tax_002',
    code: 'VAT_PLATFORM_FEE_18',
    title: 'VAT on Platform SaaS & Enterprise Subscriptions',
    ratePercent: 18.0,
    applicableTo: 'PLATFORM_FEE',
    effectiveFrom: '01 Jan 2026',
    authority: 'TRA',
    isActive: true,
  },
]

export const MOCK_FRAUD_ALERTS: FraudAlertCase[] = [
  {
    id: 'case_001',
    caseNumber: 'RISK-2026-089',
    title: 'Bot Click Flood on Kijani Solar Campaign',
    suspectEntity: 'IP Cluster 41.59.18.0/24 (Tanga Region)',
    type: 'BOT_CLICK_FLOOD',
    severity: 'HIGH',
    riskScore: 92,
    flaggedAmountTZS: 450000,
    status: 'HOLD_APPLIED',
    createdAt: 'Today, 10:55 AM',
    assignedOfficer: 'Given M.',
  },
  {
    id: 'case_002',
    caseNumber: 'RISK-2026-088',
    title: 'Self-Referral Loop Pattern Detected',
    suspectEntity: 'Partner #4912 (device ID match with business owner)',
    type: 'SELF_REFERRAL',
    severity: 'MEDIUM',
    riskScore: 78,
    flaggedAmountTZS: 120000,
    status: 'INVESTIGATING',
    createdAt: 'Yesterday, 03:20 PM',
    assignedOfficer: 'Given M.',
  },
]

export const MOCK_DISPUTES: DisputeItem[] = [
  {
    id: 'dsp_001',
    ticketNumber: 'DSP-2026-014',
    title: 'Claimed Lead Unresponsive / Fake Number',
    complainant: 'Kijani Solar Tech Ltd',
    respondent: 'Partner #3301 (Emmanuel K.)',
    dealRef: 'kijani-solar-home-kit',
    disputedAmountTZS: 45000,
    status: 'INVESTIGATING',
    openedAt: '21 Feb 2026',
    assignedTo: 'Support Officer (Juma)',
    priority: 'URGENT',
  },
  {
    id: 'dsp_002',
    ticketNumber: 'DSP-2026-012',
    title: 'Delayed Commission Approval (> 7 business days)',
    complainant: 'Partner #1108 (Salma Hassan)',
    respondent: 'Kilimo Bora Agrotech',
    dealRef: 'kilimo-bora-fertilizer-b2b',
    disputedAmountTZS: 120000,
    status: 'RESOLVED',
    openedAt: '18 Feb 2026',
    assignedTo: 'Support Officer (Juma)',
    priority: 'NORMAL',
  },
]

export const MOCK_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log_001',
    timestamp: '2026-08-24 10:42:19',
    actorId: 'usr_005',
    actorName: 'Given M. (Super Admin)',
    actorRole: 'SUPER_ADMIN',
    action: 'BUSINESS_KYB_UNDER_REVIEW_SET',
    module: 'BUSINESS',
    resourceId: 'ver_001 (MobiPay Africa)',
    ipAddress: '197.250.2.14',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    beforeState: { status: 'SUBMITTED' },
    afterState: { status: 'UNDER_REVIEW', checker: 'Given M.' },
    hashSignature: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
  },
  {
    id: 'log_002',
    timestamp: '2026-08-24 09:30:00',
    actorId: 'usr_005',
    actorName: 'Given M. (Super Admin)',
    actorRole: 'SUPER_ADMIN',
    action: 'DISBURSEMENT_BATCH_CHECKER_APPROVED',
    module: 'PAYOUTS',
    resourceId: 'batch_001 (TZS 14,060,000)',
    ipAddress: '197.250.2.14',
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64)',
    beforeState: { status: 'PENDING_MAKER' },
    afterState: { status: 'APPROVED_CHECKER' },
    hashSignature: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
  },
  {
    id: 'log_003',
    timestamp: '2026-08-24 08:15:10',
    actorId: 'system_engine',
    actorName: 'LUMO Risk Engine',
    actorRole: 'SYSTEM',
    action: 'SUSPICIOUS_CLICK_HOLD_TRIGGERED',
    module: 'RISK',
    resourceId: 'case_001',
    ipAddress: '127.0.0.1',
    userAgent: 'LumoEngine/v1.0',
    beforeState: { riskScore: 10 },
    afterState: { riskScore: 92, holdApplied: true },
    hashSignature: 'ca978112ca1bbdcafac231b39a23dc4da786eff8147c4e72b9807785afee48bb',
  },
]

export const MOCK_WEBHOOKS: WebhookIntegration[] = [
  {
    id: 'int_001',
    name: 'Vodacom M-Pesa B2C Open API',
    targetUrl: 'https://api.lumo.co.tz/v1/webhooks/mpesa-b2c',
    provider: 'VODACOM',
    apiKeyMasked: 'voda_live_99*****************88a',
    secretMasked: 'sec_****************************441b',
    events: ['payout.completed', 'payout.failed', 'balance.alert'],
    health: 'HEALTHY',
    successRate: 99.94,
    lastPing: '2 mins ago',
    pendingRetries: 0,
  },
  {
    id: 'int_002',
    name: 'Tigo Pesa Push STK Gateway',
    targetUrl: 'https://api.lumo.co.tz/v1/webhooks/tigopesa-c2b',
    provider: 'TIGO',
    apiKeyMasked: 'tigo_prod_81*****************12x',
    secretMasked: 'sec_****************************992c',
    events: ['payment.received', 'payment.reversed'],
    health: 'HEALTHY',
    successRate: 99.88,
    lastPing: '1 min ago',
    pendingRetries: 0,
  },
  {
    id: 'int_003',
    name: 'Kijani Solar Shopify Webhook Bridge',
    targetUrl: 'https://api.lumo.co.tz/v1/webhooks/merchant/kijani-solar',
    provider: 'SHOPIFY_PLUGIN',
    apiKeyMasked: 'shpat_**********************990',
    secretMasked: 'sec_****************************110z',
    events: ['orders/paid', 'fulfillments/create'],
    health: 'HEALTHY',
    successRate: 100.0,
    lastPing: '4 mins ago',
    pendingRetries: 0,
  },
]
