import type { OpportunityItem } from './types'

/**
 * 7 Verified Initial Commercial Deals (Tanzania Ecosystem)
 */
export const INITIAL_OPPORTUNITIES: OpportunityItem[] = [
  {
    id: 'opp_solar_tz_01',
    organizationId: 'org_simba_solar',
    companyName: 'Simba Solar Technologies Ltd',
    companyLogo: 'SOLAR',
    isVerified: true,
    type: 'PRODUCT_SALES',
    title: 'Jua Kali Solar Home Kits & Battery Storage Expansion',
    slug: 'simba-solar-home-kits-expansion',
    summary: 'Promote certified Tier-1 pay-as-you-go solar home electrification kits and backup inverters across Northern & Central Tanzania.',
    description: 'Simba Solar is scaling off-grid clean energy across Arusha, Kilimanjaro, and Manyara. Partners earn guaranteed cash commissions on every verified homeowner or commercial solar kit installation. Deliverables include connecting verified property owners and scheduling technical site audits.',
    category: 'Renewable Energy',
    countryCode: 'TZ',
    region: 'Northern Zone (Arusha, Kilimanjaro)',
    currency: 'TZS',
    rewardType: 'PERCENTAGE_COMMISSION',
    rewardDisplay: 'TZS 85,000 / Kit (15%)',
    rewardDetail: '15% commission on gross kit value (Average TZS 85,000 payout per completed installation)',
    potentialBonus: 'TZS 250,000 monthly bonus on reaching 10 sales milestones',
    totalBudgetTZS: BigInt(2500000000), // TZS 25,000,000 in minor units
    spentBudgetTZS: BigInt(34000000),
    maxPartners: 50,
    activePartnerCount: 18,
    isFeatured: true,
    featuredImageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1400&h=900&q=90',
    promoVideoUrl: 'https://www.youtube.com/watch?v=0hYq5eZt9Zg',
    galleryImageUrls: [
      'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=1400&h=900&q=90',
      'https://images.unsplash.com/photo-1508873696983-2df5293cb395?auto=format&fit=crop&w=1400&h=900&q=90',
    ],
    termsAndConditions: 'Payouts settled every Friday via direct M-Pesa. Customer must complete initial deposit and technician installation signoff.',
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-20T08:00:00Z'),
    expiryDate: new Date('2026-12-31T23:59:59Z'),
  },
  {
    id: 'opp_agrotech_tz_02',
    organizationId: 'org_kilimo_iot',
    companyName: 'Kilimo IoT Innovations Ltd',
    companyLogo: 'KILIMO',
    isVerified: true,
    type: 'B2B_INTRODUCTION',
    title: 'Kilimo Bora Smart IoT Soil & Irrigation Moisture Sensors',
    slug: 'kilimo-bora-smart-iot-soil-sensors',
    summary: 'Introduce commercial grain, avocado, and horticulture farm owners to precision IoT soil monitoring and automated drip irrigation controllers.',
    description: 'We help agricultural enterprises reduce water wastage and boost crop yields by up to 35%. Partners introduce farm managers and agricultural cooperatives. Payout is triggered when an agro-enterprise signs a demonstration pilot or purchase contract.',
    category: 'Agriculture & Agrotech',
    countryCode: 'TZ',
    region: 'Morogoro, Iringa & Mbeya',
    currency: 'TZS',
    rewardType: 'FIXED_COMMISSION',
    rewardDisplay: 'TZS 250,000 / Farm Deal',
    rewardDetail: 'Fixed bounty of TZS 250,000 per verified farm deployment contract signed',
    potentialBonus: '5% lifetime hardware renewal royalty for 12 months',
    totalBudgetTZS: BigInt(5000000000), // TZS 50,000,000
    spentBudgetTZS: BigInt(75000000),
    maxPartners: 30,
    activePartnerCount: 12,
    isFeatured: true,
    featuredImageUrl: 'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=1400&h=900&q=90',
    promoVideoUrl: 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
    galleryImageUrls: [
      'https://images.unsplash.com/photo-1586771107445-d3ca888129ff?auto=format&fit=crop&w=1400&h=900&q=90',
    ],
    termsAndConditions: 'Lead must hold at least 5 acres under active irrigation and participate in a verified technical demonstration.',
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-21T09:30:00Z'),
    expiryDate: new Date('2026-11-30T23:59:59Z'),
  },
  {
    id: 'opp_fintech_pos_03',
    organizationId: 'org_twiga_fintech',
    companyName: 'Twiga Fintech Solutions Ltd',
    companyLogo: 'TWIGA',
    isVerified: true,
    type: 'CUSTOMER_ACQUISITION',
    title: 'Twiga Smart POS & All-in-One Mobile Money Retail Suite',
    slug: 'twiga-smart-pos-retail-suite',
    summary: 'Onboard retail shops, pharmacies, supermarkets, and restaurants to the Twiga Android POS terminal with multi-network mobile money settlement.',
    description: 'Twiga POS allows small and medium merchants in Tanzania to accept Vodacom M-Pesa, Tigo Pesa, Airtel Money, and Visa/Mastercard on one single device with automated TRA fiscal receipt (EFD) printing.',
    category: 'Fintech & Payments',
    countryCode: 'TZ',
    region: 'Dar es Salaam & Pwani',
    currency: 'TZS',
    rewardType: 'COST_PER_ACQUISITION',
    rewardDisplay: 'TZS 45,000 / Merchant',
    rewardDetail: 'Instant TZS 45,000 payout upon merchant terminal activation and first 5 processed transactions',
    potentialBonus: 'TZS 100,000 milestone bonus for every 10 active onboarded shops per week',
    totalBudgetTZS: BigInt(4000000000), // TZS 40,000,000
    spentBudgetTZS: BigInt(125000000),
    maxPartners: 100,
    activePartnerCount: 42,
    isFeatured: true,
    featuredImageUrl: 'https://images.unsplash.com/photo-1556742049-0a67e557224f?auto=format&fit=crop&w=1400&h=900&q=90',
    promoVideoUrl: 'https://www.youtube.com/watch?v=0hYq5eZt9Zg',
    galleryImageUrls: [
      'https://images.unsplash.com/photo-1556742049-0a67e557224f?auto=format&fit=crop&w=1400&h=900&q=90',
    ],
    termsAndConditions: 'Merchant must provide valid TIN certificate or business license and process at least TZS 100,000 in transaction volume.',
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-22T10:00:00Z'),
    expiryDate: new Date('2026-12-15T23:59:59Z'),
  },
  {
    id: 'opp_kazitech_hr_04',
    organizationId: 'org_kazitech',
    companyName: 'KaziTech Software Africa',
    companyLogo: 'KAZI',
    isVerified: true,
    type: 'QUALIFIED_LEADS',
    title: 'KaziConnect Cloud HR, Payroll & NSSF/WCF Compliance Suite',
    slug: 'kaziconnect-cloud-hr-payroll-suite',
    summary: 'Generate qualified demo meetings with Finance Directors, HR Managers, and CEOs of Tanzanian companies with 20+ employees.',
    description: 'KaziConnect automates Tanzanian payroll, TRA PAYE, SDL, NSSF, WCF, and HESLB deductions in compliance with Ministry of Labour regulations. Earn fixed fees simply for setting up qualified executive demonstration meetings.',
    category: 'Enterprise Software',
    countryCode: 'TZ',
    region: 'All Tanzania (Dar, Dodoma, Arusha)',
    currency: 'TZS',
    rewardType: 'COST_PER_LEAD',
    rewardDisplay: 'TZS 120,000 / Executive Demo',
    rewardDetail: 'TZS 120,000 paid for every completed 30-minute product demonstration with an authorized HR/Finance buyer',
    potentialBonus: '10% closing commission if lead converts to annual contract within 60 days',
    totalBudgetTZS: BigInt(3000000000), // TZS 30,000,000
    spentBudgetTZS: BigInt(60000000),
    maxPartners: 25,
    activePartnerCount: 9,
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&h=900&q=90',
    promoVideoUrl: 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
    galleryImageUrls: [
      'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1400&h=900&q=90',
    ],
    termsAndConditions: 'Prospect must have minimum 20 headcount and participate in the virtual or in-person product walkthrough.',
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-23T11:00:00Z'),
    expiryDate: new Date('2026-11-20T23:59:59Z'),
  },
  {
    id: 'opp_safari_tourism_05',
    organizationId: 'org_serengeti_wilds',
    companyName: 'Serengeti Expeditions & Safari Co.',
    companyLogo: 'SAFARI',
    isVerified: true,
    type: 'PRODUCT_SALES',
    title: 'Serengeti & Ngorongoro Luxury Safari Vacation Packages',
    slug: 'serengeti-ngorongoro-luxury-safari',
    summary: 'Refer domestic and international tourist groups, corporate retreats, and holidaymakers for luxury 4x4 guided wildlife safaris.',
    description: 'Promote 3-day to 7-day all-inclusive safari itineraries across Serengeti National Park, Ngorongoro Crater, and Lake Manyara with luxury tented camps and professional multilingual guides.',
    category: 'Hospitality & Tourism',
    countryCode: 'TZ',
    region: 'Kilimanjaro, Arusha & Zanzibar',
    currency: 'TZS',
    rewardType: 'PERCENTAGE_COMMISSION',
    rewardDisplay: 'TZS 350,000 / Booking (10%)',
    rewardDetail: '10% commission on total package value (Average payout TZS 350,000 per booking referral)',
    potentialBonus: 'Free 2-day Ngorongoro weekend getaway for top performing partner every quarter',
    totalBudgetTZS: BigInt(6000000000), // TZS 60,000,000
    spentBudgetTZS: BigInt(180000000),
    maxPartners: 40,
    activePartnerCount: 23,
    isFeatured: true,
    featuredImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1400&h=900&q=90',
    promoVideoUrl: 'https://www.youtube.com/watch?v=0hYq5eZt9Zg',
    galleryImageUrls: [
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1400&h=900&q=90',
    ],
    termsAndConditions: 'Commission released immediately upon client paying the 30% reservation deposit.',
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-24T09:00:00Z'),
    expiryDate: new Date('2027-01-31T23:59:59Z'),
  },
  {
    id: 'opp_afyabora_health_06',
    organizationId: 'org_afyabora_health',
    companyName: 'AfyaBora Digital Health Tanzania',
    companyLogo: 'AFYA',
    isVerified: true,
    type: 'DISTRIBUTOR_SEARCH',
    title: 'AfyaBora Telemedicine & Diagnostic Health Kiosks',
    slug: 'afyabora-telemedicine-kiosks',
    summary: 'Secure regional hospital, pharmacy, and clinic distribution partnerships for automated health checkup kiosks and doctor video triage.',
    description: 'AfyaBora kiosks provide rapid blood pressure, blood glucose, ECG, and BMI readings with direct tele-consultations to licensed medical officers. We seek regional business developers to place kiosks in private clinics and corporate premises.',
    category: 'Healthcare & Wellness',
    countryCode: 'TZ',
    region: 'Mwanza, Lake Zone & Dodoma',
    currency: 'TZS',
    rewardType: 'FIXED_COMMISSION',
    rewardDisplay: 'TZS 500,000 / Distributor Hub',
    rewardDetail: 'Fixed payout of TZS 500,000 for each clinic or pharmacy that adopts and deploys a diagnostic kiosk unit',
    potentialBonus: 'Monthly recurring data maintenance rev-share of TZS 50,000 per active kiosk',
    totalBudgetTZS: BigInt(4500000000), // TZS 45,000,000
    spentBudgetTZS: BigInt(90000000),
    maxPartners: 20,
    activePartnerCount: 7,
    isFeatured: false,
    featuredImageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1400&h=900&q=90',
    promoVideoUrl: 'https://www.youtube.com/watch?v=ScMzIvxBSi4',
    galleryImageUrls: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1400&h=900&q=90',
    ],
    termsAndConditions: 'Clinic or health center must be registered with the Ministry of Health (MOH) and sign a 1-year service agreement.',
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-24T14:00:00Z'),
    expiryDate: new Date('2026-12-31T23:59:59Z'),
  },
  {
    id: 'opp_emobility_boda_07',
    organizationId: 'org_dar_emobility',
    companyName: 'Zanzibar E-Mobility Group Ltd',
    companyLogo: 'EVTZ',
    isVerified: true,
    type: 'PRODUCT_SALES',
    title: 'Dar Express Electric Cargo Boda & Battery Swap Fleet',
    slug: 'dar-express-electric-cargo-boda',
    summary: 'Sell and lease rugged electric motorbikes (Boda Boda) with swap battery network subscriptions to commercial couriers and riders.',
    description: 'Electric bodas reduce daily operating fuel costs by up to 60% with instant 2-minute battery swap stations across Dar es Salaam. Partners earn commissions on each rider fleet package financed or purchased outright.',
    category: 'Logistics & Transportation',
    countryCode: 'TZ',
    region: 'Dar es Salaam & Zanzibar',
    currency: 'TZS',
    rewardType: 'FIXED_COMMISSION',
    rewardDisplay: 'TZS 180,000 / Electric Boda',
    rewardDetail: 'TZS 180,000 paid per approved electric motorcycle sale or lease agreement finalized',
    potentialBonus: 'TZS 500,000 bonus for corporate fleet orders of 5+ bikes in a single transaction',
    totalBudgetTZS: BigInt(3500000000), // TZS 35,000,000
    spentBudgetTZS: BigInt(110000000),
    maxPartners: 60,
    activePartnerCount: 31,
    isFeatured: true,
    featuredImageUrl: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1400&h=900&q=90',
    promoVideoUrl: 'https://www.youtube.com/watch?v=0hYq5eZt9Zg',
    galleryImageUrls: [
      'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1400&h=900&q=90',
    ],
    termsAndConditions: 'Rider or fleet company must complete identity KYC verification and pay the initial lease down payment.',
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-25T04:00:00Z'),
    expiryDate: new Date('2027-02-28T23:59:59Z'),
  },
]
