import type { OpportunityItem } from './types'

export const INITIAL_OPPORTUNITIES: OpportunityItem[] = [
  {
    id: 'opp_kijani_solar',
    organizationId: 'org_kijani',
    companyName: 'Kijani Solar Tech',
    companyLogo: 'KS',
    isVerified: true,
    type: 'CUSTOMER_ACQUISITION',
    title: 'Power the Next 1,000 Homes in Rural & Peri-Urban Tanzania',
    slug: 'kijani-solar-home-systems',
    summary: 'Earn TZS 45,000 for every verified household solar power system installation completed through your referral.',
    description: 'Kijani Solar is expanding access to clean solar home lighting and appliances across Tanzania. As a Partner, you connect homeowners, rural cooperatives, and peri-urban small businesses to our flexible pay-as-you-go solar systems. Earnings are disbursed directly via M-Pesa upon certified technician installation and down-payment confirmation.',
    category: 'Renewable Energy',
    countryCode: 'TZ',
    region: 'Dar es Salaam, Arusha, Morogoro, Mwanza',
    currency: 'TZS',
    rewardType: 'COST_PER_ACQUISITION',
    rewardDisplay: 'TZS 45,000',
    rewardDetail: 'per verified installation',
    potentialBonus: 'TZS 250,000 milestone bonus at 10 installations',
    featuredImageUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80',
    totalBudgetTZS: BigInt(4500000000),
    spentBudgetTZS: BigInt(1240000000),
    maxPartners: 150,
    activePartnerCount: 42,
    isFeatured: true,
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-01'),
  },
  {
    id: 'opp_mobipay_merchants',
    organizationId: 'org_mobipay',
    companyName: 'MobiPay Africa',
    companyLogo: 'MP',
    isVerified: true,
    type: 'QUALIFIED_LEADS',
    title: 'Onboard SME Retailers & Dukas to MobiPay QR & Card POS',
    slug: 'mobipay-sme-onboarding',
    summary: 'Earn TZS 25,000 for every retail merchant who activates their payment terminal and processes 3+ transactions.',
    description: 'Help Tanzanian retail shop owners, restaurants, and pharmacy owners accept cashless mobile money and cards. Partners introduce merchant owners to the MobiPay app or POS terminal. Commission is validated once the merchant completes KYC and processes at least TZS 50,000 in customer transactions.',
    category: 'Fintech & Payments',
    countryCode: 'TZ',
    region: 'Nationwide Tanzania',
    currency: 'TZS',
    rewardType: 'COST_PER_LEAD',
    rewardDisplay: 'TZS 25,000',
    rewardDetail: 'per activated merchant',
    potentialBonus: 'TZS 500,000 bonus at 25 active merchants',
    featuredImageUrl: 'https://images.unsplash.com/photo-1556742049-0a67e557b640?auto=format&fit=crop&w=800&q=80',
    totalBudgetTZS: BigInt(3000000000),
    spentBudgetTZS: BigInt(890000000),
    maxPartners: 200,
    activePartnerCount: 78,
    isFeatured: true,
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-05'),
  },
  {
    id: 'opp_safaribox_travel',
    organizationId: 'org_safaribox',
    companyName: 'SafariBox Serengeti',
    companyLogo: 'SB',
    isVerified: true,
    type: 'CONTENT_CREATION',
    title: 'Visual Storytelling & Wilderness Influencer Campaign',
    slug: 'safaribox-creator-campaign',
    summary: 'Earn TZS 450,000 fixed fee + 8% revenue share on all safari lodge bookings generated through your creator codes.',
    description: 'We are inviting verified East African travel photographers, videographers, and lifestyle creators to produce original reels and photo essays showcasing Serengeti & Ngorongoro boutique tented camps. LUMO Deal Room coordinates deliverable approvals and milestones.',
    category: 'Travel & Hospitality',
    countryCode: 'TZ',
    region: 'Arusha, Zanzibar, Kilimanjaro',
    currency: 'TZS',
    rewardType: 'HYBRID',
    rewardDisplay: 'TZS 450,000 + 8%',
    rewardDetail: 'fixed fee + booking revenue share',
    potentialBonus: 'Complimentary 3-day lodge stay at 5 bookings',
    featuredImageUrl: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80',
    totalBudgetTZS: BigInt(1500000000),
    spentBudgetTZS: BigInt(450000000),
    maxPartners: 20,
    activePartnerCount: 12,
    isFeatured: true,
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-10'),
  },
  {
    id: 'opp_kilimofresh_distributors',
    organizationId: 'org_kilimo',
    companyName: 'Kilimo Fresh Organics',
    companyLogo: 'KF',
    isVerified: true,
    type: 'DISTRIBUTOR_SEARCH',
    title: 'Find Regional Wholesale Distributors for Organic Fruit Juices',
    slug: 'kilimofresh-regional-distributor-bounty',
    summary: 'Earn TZS 1,500,000 finder reward for introducing a qualified regional food and beverage distributor.',
    description: 'Kilimo Fresh is scaling distribution of locally sourced organic passion, mango, and avocado oil products across East Africa. We are seeking commercial introducers who can connect us with licensed FMCG distributors in Mwanza, Mbeya, Dodoma, or Kampala. Bounty is paid upon contract execution and first purchase order clearance.',
    category: 'Agriculture & FMCG',
    countryCode: 'TZ',
    region: 'Mwanza, Mbeya, Dodoma, Tanga',
    currency: 'TZS',
    rewardType: 'FIXED_COMMISSION',
    rewardDisplay: 'TZS 1,500,000',
    rewardDetail: 'finder reward per signed distributor',
    potentialBonus: '1.5% override on year-1 wholesale shipments',
    featuredImageUrl: 'https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?auto=format&fit=crop&w=800&q=80',
    totalBudgetTZS: BigInt(1000000000),
    spentBudgetTZS: BigInt(300000000),
    maxPartners: 30,
    activePartnerCount: 9,
    isFeatured: false,
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-12'),
  },
  {
    id: 'opp_bunitech_erp',
    organizationId: 'org_bunitech',
    companyName: 'BuniTech Cloud ERP',
    companyLogo: 'BT',
    isVerified: true,
    type: 'B2B_INTRODUCTION',
    title: 'B2B Commercial Introductions for Cloud ERP & Payroll',
    slug: 'bunitech-enterprise-erp-referrals',
    summary: 'Earn TZS 350,000 per qualified executive demo meeting + 12% recurring first-year contract value.',
    description: 'BuniTech builds localized accounting, TRA VFD integration, and payroll software for manufacturing, logistics, and hospitality businesses with 20+ employees. Introduce the CFO or Managing Director, attend the introductory discovery session, and earn upon qualified presentation.',
    category: 'Technology & Enterprise',
    countryCode: 'TZ',
    region: 'Dar es Salaam, Nairobi, Kigali',
    currency: 'TZS',
    rewardType: 'HYBRID',
    rewardDisplay: 'TZS 350,000 + 12%',
    rewardDetail: 'per qualified demo + 12% 1st-yr contract',
    potentialBonus: 'TZS 2,000,000 bonus on contracts over TZS 50M',
    featuredImageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80',
    totalBudgetTZS: BigInt(800000000),
    spentBudgetTZS: BigInt(210000000),
    maxPartners: 40,
    activePartnerCount: 16,
    isFeatured: true,
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-14'),
  },
  {
    id: 'opp_twiga_coffee',
    organizationId: 'org_twiga',
    companyName: 'Twiga Mountain Coffee',
    companyLogo: 'TC',
    isVerified: true,
    type: 'PRODUCT_SALES',
    title: 'Promote Single-Origin Kilimanjaro Peaberry & Specialty Coffee',
    slug: 'twiga-specialty-coffee-sales',
    summary: 'Earn 15% commission on all retail web orders and corporate gift box purchases placed through your tracking links.',
    description: 'Twiga Coffee brings farm-direct Arabica and Peaberry roasts from Mount Kilimanjaro slopes to coffee lovers across the globe. Share your custom tracking links, promo codes, or QR menus with your network, office hubs, and expat communities.',
    category: 'Food & Beverage',
    countryCode: 'TZ',
    region: 'Nationwide & International Shipping',
    currency: 'TZS',
    rewardType: 'PERCENTAGE_COMMISSION',
    rewardDisplay: '15% Commission',
    rewardDetail: 'on all completed customer checkouts',
    potentialBonus: 'TZS 100,000 bonus every 20 orders',
    featuredImageUrl: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=800&q=80',
    totalBudgetTZS: BigInt(500000000),
    spentBudgetTZS: BigInt(180000000),
    maxPartners: 300,
    activePartnerCount: 112,
    isFeatured: false,
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-15'),
  },
  {
    id: 'opp_shuleplus_edtech',
    organizationId: 'org_shuleplus',
    companyName: 'ShulePlus Learning',
    companyLogo: 'SP',
    isVerified: true,
    type: 'SUBSCRIPTION_PROMOTION',
    title: 'Primary & Secondary Interactive Curriculum Subscriptions',
    slug: 'shuleplus-learning-subscriptions',
    summary: 'Earn TZS 12,000 for every parent who subscribes their student to the NECTA-aligned exam prep app.',
    description: 'ShulePlus provides video lessons, animated quizzes, and past NECTA exam solutions in both Swahili and English. Promote to PTA groups, parent communities, and educational centers. Commission unlocks instantly after 14-day subscription retention.',
    category: 'Education & EdTech',
    countryCode: 'TZ',
    region: 'Tanzania (All Regions)',
    currency: 'TZS',
    rewardType: 'COST_PER_ACQUISITION',
    rewardDisplay: 'TZS 12,000',
    rewardDetail: 'per annual parent subscription',
    potentialBonus: 'TZS 300,000 bonus at 50 subscriptions',
    featuredImageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=800&q=80',
    totalBudgetTZS: BigInt(400000000),
    spentBudgetTZS: BigInt(96000000),
    maxPartners: 250,
    activePartnerCount: 65,
    isFeatured: false,
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-16'),
  },
  {
    id: 'opp_mmbao_sourcing',
    organizationId: 'org_mmbao',
    companyName: 'M-Mbao Industrial Wood',
    companyLogo: 'MM',
    isVerified: true,
    type: 'REVERSE_SOURCING',
    title: 'Reverse-Sourcing Bounty: Certified Teak & Eucalyptus Hardwood Suppliers',
    slug: 'mmbao-timber-supplier-bounty',
    summary: 'Earn TZS 800,000 fulfillment bounty by sourcing verified sustainable timber concessionaires.',
    description: 'We are seeking timber harvesting suppliers holding valid TFS (Tanzania Forest Services) certificates for upcoming residential construction projects in Dar es Salaam and Dodoma. Complete the commercial introduction and submit harvest license evidence to claim bounty.',
    category: 'Construction & Sourcing',
    countryCode: 'TZ',
    region: 'Tanga, Morogoro, Iringa, Ruvuma',
    currency: 'TZS',
    rewardType: 'FIXED_COMMISSION',
    rewardDisplay: 'TZS 800,000',
    rewardDetail: 'per qualified and contracted supplier',
    potentialBonus: 'B2B repeat bonus on volume shipments',
    featuredImageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=800&q=80',
    totalBudgetTZS: BigInt(800000000),
    spentBudgetTZS: BigInt(160000000),
    maxPartners: 25,
    activePartnerCount: 8,
    isFeatured: false,
    status: 'PUBLISHED',
    createdAt: new Date('2026-08-18'),
  },
]
