'use client'
import { useEffect, useState } from 'react'

export default function SubmitHotDeal() {
  const [organizations, setOrganizations] = useState<{ id: string; legalName: string }[]>([])
  const [message, setMessage] = useState('Loading merchant access…')
  const [busy, setBusy] = useState(false)
  const [requestId, setRequestId] = useState('')
  useEffect(() => { void fetch('/api/hot-deals/submission').then(async r => { const data = await r.json(); if (!r.ok) throw new Error(data.error); setOrganizations(data.organizations); setRequestId(crypto.randomUUID()); setMessage(data.organizations.length ? '' : 'An active merchant organization is required to submit a deal.') }).catch(e => setMessage(e.message)) }, [])
  return <main className="mx-auto max-w-3xl px-4 py-8"><h1 className="text-3xl font-bold">Submit a Private Hot Deal</h1><p className="mt-3 text-sm leading-6 text-slate-500">Offer a verified asset, rental, service or commercial opportunity. Ownership evidence, clear reward terms and confirmed pre-funding are required before publication.</p>{message && <p className="mt-5 rounded-xl border bg-white p-4 text-sm" role="status">{message}</p>}{organizations.length > 0 && <form className="mt-6 grid gap-5 rounded-2xl border bg-white p-6" onSubmit={async e => {
    e.preventDefault(); setBusy(true)
    try {
      const form = new FormData(e.currentTarget)
      const upload = new FormData(); upload.set('file', form.get('evidence')!)
      const uploaded = await fetch('/api/hot-deals/files', { method: 'POST', body: upload }); const file = await uploaded.json(); if (!uploaded.ok) throw new Error(file.error)
      const money = (key: string) => (BigInt(String(form.get(key))) * 100n).toString()
      const body = { requestId, organizationId: form.get('organizationId'), title: form.get('title'), teaserTitle: form.get('teaserTitle'), category: form.get('category'), location: form.get('location'), description: form.get('description'), terms: form.get('terms'), rewardTrigger: form.get('rewardTrigger'), ownerEvidenceFileId: file.id, maximumPartnerSlots: Number(form.get('slots')), inventoryTotal: Number(form.get('units')), rewardBudget: money('budget'), rewardPerVerifiedOutcome: money('reward'), dealCapacityType: form.get('capacity'), privateAccessEnabled: form.has('private') }
      const response = await fetch('/api/hot-deals/submission', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error)
      setMessage('Your opportunity is under review. The compliance team will review evidence and confirm payment-partner funding before publication.')
    } catch (e) { setMessage(e instanceof Error ? e.message : 'Submission failed.') } finally { setBusy(false) }
  }}><label className="text-sm">Merchant organization<select name="organizationId" className="mt-1 w-full rounded-xl border p-3">{organizations.map(o => <option key={o.id} value={o.id}>{o.legalName}</option>)}</select></label>{[{ name: 'title', label: 'Full deal title' }, { name: 'teaserTitle', label: 'Public teaser title (no owner identity or confidential details)' }, { name: 'category', label: 'Category (e.g. Vehicle Sale or Rental Opportunity)' }, { name: 'location', label: 'General location (no exact address)' }].map(field => <label className="text-sm" key={field.name}>{field.label}<input name={field.name} required minLength={3} maxLength={100} className="mt-1 w-full rounded-xl border p-3" /></label>)}{[{ name: 'description', label: 'Full verified details and price terms', min: 20 }, { name: 'terms', label: 'Participation agreement, attribution and dispute rules', min: 30 }, { name: 'rewardTrigger', label: 'Objective evidence required to earn a reward', min: 20 }].map(field => <label key={field.name} className="text-sm">{field.label}<textarea name={field.name} rows={4} required minLength={field.min} maxLength={field.name === 'rewardTrigger' ? 2000 : 20000} className="mt-1 w-full rounded-xl border p-3" /></label>)}<div className="grid gap-4 sm:grid-cols-2">{[{ name: 'reward', label: 'Reward per outcome (TZS)' }, { name: 'budget', label: 'Total reward budget (TZS)' }, { name: 'units', label: 'Units / conversion capacity' }, { name: 'slots', label: 'Maximum participating partners' }].map(field => <label className="text-sm" key={field.name}>{field.label}<input type="number" name={field.name} required min={1} step={1} className="mt-1 w-full rounded-xl border p-3" /></label>)}</div><label className="text-sm">Capacity type<select name="capacity" className="mt-1 w-full rounded-xl border p-3">{['ONE_UNIT', 'MULTI_UNIT', 'UNLIMITED', 'LEAD_LIMIT'].map(c => <option key={c}>{c}</option>)}</select></label><label className="flex gap-3 text-sm"><input name="private" type="checkbox" defaultChecked />Private Members get exclusive access for the first 24 hours.</label><label className="text-sm">Private ownership / authority evidence (PDF, PNG or JPEG; 5 MB)<input name="evidence" type="file" required accept="application/pdf,image/png,image/jpeg" className="mt-2 block w-full text-sm" /></label><button disabled={busy} className="rounded-xl bg-orange-600 p-3 font-semibold text-white disabled:opacity-50">{busy ? 'Submitting…' : 'Submit for compliance review'}</button></form>}</main>
}
